[[redirects]]
  from = "/api/*"
  to = "https://app.coalescesoftware.io/scheduler/:splat"
  status = 200
  force = true


[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
  Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
